pos(complication(patient11)).
pos(complication(patient14)).
pos(complication(patient6)).
pos(complication(patient3)).
pos(complication(patient93)).
pos(complication(patient35)).
pos(complication(patient18)).
pos(complication(patient7)).
pos(complication(patient28)).
pos(complication(patient58)).
pos(complication(patient40)).
pos(complication(patient66)).
pos(complication(patient82)).
pos(complication(patient73)).
pos(complication(patient37)).
pos(complication(patient67)).
pos(complication(patient94)).
pos(complication(patient50)).
pos(complication(patient15)).
pos(complication(patient103)).
pos(complication(patient26)).
neg(complication(patient12)).
neg(complication(patient105)).
neg(complication(patient44)).
neg(complication(patient111)).
neg(complication(patient39)).
neg(complication(patient46)).
neg(complication(patient1)).
neg(complication(patient98)).
neg(complication(patient48)).
neg(complication(patient49)).
neg(complication(patient59)).
neg(complication(patient32)).
neg(complication(patient63)).
neg(complication(patient114)).
