pos(complication(patient64)).
pos(complication(patient69)).
pos(complication(patient15)).
pos(complication(patient115)).
pos(complication(patient92)).
pos(complication(patient55)).
pos(complication(patient42)).
pos(complication(patient117)).
pos(complication(patient99)).
pos(complication(patient7)).
pos(complication(patient3)).
pos(complication(patient4)).
pos(complication(patient83)).
pos(complication(patient14)).
pos(complication(patient16)).
pos(complication(patient20)).
pos(complication(patient35)).
pos(complication(patient40)).
pos(complication(patient50)).
pos(complication(patient5)).
pos(complication(patient17)).
neg(complication(patient110)).
neg(complication(patient76)).
neg(complication(patient85)).
neg(complication(patient108)).
neg(complication(patient53)).
neg(complication(patient101)).
neg(complication(patient118)).neg(complication(patient107)).
neg(complication(patient32)).
neg(complication(patient57)).
neg(complication(patient49)).
neg(complication(patient68)).
neg(complication(patient75)).
neg(complication(patient46)).
