pos(carcinogen(d0)).
pos(carcinogen(d1)).
pos(carcinogen(d3)).
pos(carcinogen(d4)).
pos(carcinogen(d8)).
pos(carcinogen(d9)).
pos(carcinogen(d10)).
pos(carcinogen(d11)).
pos(carcinogen(d13)).
pos(carcinogen(d19)).
pos(carcinogen(d20)).
pos(carcinogen(d21)).
neg(carcinogen(d2)).
neg(carcinogen(d5)).
neg(carcinogen(d6)).
neg(carcinogen(d7)).
neg(carcinogen(d12)).
neg(carcinogen(d14)).
neg(carcinogen(d15)).
neg(carcinogen(d16)).
neg(carcinogen(d17)).
neg(carcinogen(d18)).