pos(complication(patient43)).
pos(complication(patient81)).
pos(complication(patient6)).
pos(complication(patient52)).
pos(complication(patient65)).
pos(complication(patient66)).
pos(complication(patient72)).
pos(complication(patient19)).
pos(complication(patient88)).
pos(complication(patient36)).
pos(complication(patient87)).
pos(complication(patient112)).
pos(complication(patient93)).
pos(complication(patient82)).
pos(complication(patient116)).
pos(complication(patient58)).
pos(complication(patient71)).
pos(complication(patient27)).
pos(complication(patient86)).
pos(complication(patient30)).
pos(complication(patient10)).
pos(complication(patient22)).
neg(complication(patient62)).
neg(complication(patient96)).
neg(complication(patient34)).
neg(complication(patient111)).
neg(complication(patient29)).
neg(complication(patient47)).
neg(complication(patient109)).
neg(complication(patient61)).
neg(complication(patient84)).
neg(complication(patient98)).
neg(complication(patient56)).
neg(complication(patient105)).
neg(complication(patient59)).
neg(complication(patient113)).
