:-dynamic pos/1.
:-dynamic neg/1. 
:-dynamic complication/1.
pos(complication(patient2)).
pos(complication(patient3)).
pos(complication(patient4)).
pos(complication(patient5)).
pos(complication(patient6)).
pos(complication(patient7)).
pos(complication(patient8)).
pos(complication(patient9)).
pos(complication(patient10)).
pos(complication(patient11)).
pos(complication(patient13)).
pos(complication(patient14)).
pos(complication(patient15)).
pos(complication(patient16)).
pos(complication(patient17)).
pos(complication(patient18)).
pos(complication(patient19)).
pos(complication(patient20)).
pos(complication(patient21)).
pos(complication(patient23)).
pos(complication(patient25)).
pos(complication(patient26)).
pos(complication(patient28)).
pos(complication(patient30)).
pos(complication(patient31)).
pos(complication(patient33)).
pos(complication(patient35)).
pos(complication(patient36)).
pos(complication(patient37)).
pos(complication(patient40)).
pos(complication(patient42)).
pos(complication(patient43)).
pos(complication(patient45)).
pos(complication(patient50)).
pos(complication(patient54)).
pos(complication(patient55)).
pos(complication(patient58)).
pos(complication(patient64)).
pos(complication(patient66)).
pos(complication(patient67)).
pos(complication(patient69)).
pos(complication(patient70)).
pos(complication(patient71)).
pos(complication(patient72)).
pos(complication(patient73)).
pos(complication(patient74)).
pos(complication(patient80)).
pos(complication(patient82)).
pos(complication(patient83)).
pos(complication(patient86)).
pos(complication(patient87)).
pos(complication(patient88)).
pos(complication(patient89)).
pos(complication(patient91)).
pos(complication(patient92)).
pos(complication(patient93)).
pos(complication(patient94)).
pos(complication(patient95)).
pos(complication(patient99)).
pos(complication(patient103)).
pos(complication(patient104)).
pos(complication(patient112)).
pos(complication(patient115)).
pos(complication(patient116)).
pos(complication(patient117)).
neg(complication(patient1)).
neg(complication(patient12)).
neg(complication(patient24)).
neg(complication(patient29)).
neg(complication(patient32)).
neg(complication(patient38)).
neg(complication(patient39)).
neg(complication(patient41)).
neg(complication(patient44)).
neg(complication(patient46)).
neg(complication(patient47)).
neg(complication(patient48)).
neg(complication(patient49)).
neg(complication(patient51)).
neg(complication(patient53)).
neg(complication(patient56)).
neg(complication(patient59)).
neg(complication(patient61)).
neg(complication(patient62)).
neg(complication(patient63)).
neg(complication(patient68)).
neg(complication(patient75)).
neg(complication(patient76)).
neg(complication(patient77)).
neg(complication(patient78)).
neg(complication(patient79)).
neg(complication(patient84)).
neg(complication(patient85)).
neg(complication(patient97)).
neg(complication(patient98)).
neg(complication(patient100)).
neg(complication(patient101)).
neg(complication(patient102)).
neg(complication(patient105)).
neg(complication(patient106)).
neg(complication(patient108)).
neg(complication(patient109)).
neg(complication(patient110)).
neg(complication(patient111)).
neg(complication(patient113)).
neg(complication(patient114)).
neg(complication(patient118)).