pos(carcinogen(d0)).
pos(carcinogen(d1)).
pos(carcinogen(d2)).
pos(carcinogen(d3)).
pos(carcinogen(d4)).
pos(carcinogen(d10)).
pos(carcinogen(d12)).
pos(carcinogen(d13)).
pos(carcinogen(d17)).
pos(carcinogen(d18)).
pos(carcinogen(d19)).
pos(carcinogen(d20)).
pos(carcinogen(d21)).
pos(carcinogen(d22)).
pos(carcinogen(d23)).
pos(carcinogen(d24)).
pos(carcinogen(d25)).
pos(carcinogen(d27)).
pos(carcinogen(d28)).
pos(carcinogen(d30)).
pos(carcinogen(d31)).
pos(carcinogen(d33)).
pos(carcinogen(d37)).
pos(carcinogen(d39)).
pos(carcinogen(d40)).
pos(carcinogen(d41)).
pos(carcinogen(d44)).
pos(carcinogen(d45)).
pos(carcinogen(d46)).
pos(carcinogen(d47)).
pos(carcinogen(d48)).
pos(carcinogen(d49)).
pos(carcinogen(d52)).
pos(carcinogen(d53)).
pos(carcinogen(d54)).
pos(carcinogen(d57)).
pos(carcinogen(d59)).
pos(carcinogen(d60)).
pos(carcinogen(d62)).
pos(carcinogen(d67)).
pos(carcinogen(d70)).
pos(carcinogen(d71)).
pos(carcinogen(d73)).
pos(carcinogen(d75)).
pos(carcinogen(d77)).
pos(carcinogen(d78)).
pos(carcinogen(d81)).
pos(carcinogen(d82)).
pos(carcinogen(d85)).
neg(carcinogen(d5)).
neg(carcinogen(d6)).
neg(carcinogen(d7)).
neg(carcinogen(d8)).
neg(carcinogen(d9)).
neg(carcinogen(d11)).
neg(carcinogen(d14)).
neg(carcinogen(d15)).
neg(carcinogen(d16)).
neg(carcinogen(d26)).
neg(carcinogen(d29)).
neg(carcinogen(d32)).
neg(carcinogen(d34)).
neg(carcinogen(d35)).
neg(carcinogen(d36)).
neg(carcinogen(d38)).
neg(carcinogen(d42)).
neg(carcinogen(d43)).
neg(carcinogen(d50)).
neg(carcinogen(d51)).
neg(carcinogen(d55)).
neg(carcinogen(d56)).
neg(carcinogen(d58)).
neg(carcinogen(d61)).
neg(carcinogen(d63)).
neg(carcinogen(d64)).
neg(carcinogen(d65)).
neg(carcinogen(d66)).
neg(carcinogen(d68)).
neg(carcinogen(d69)).
neg(carcinogen(d72)).
neg(carcinogen(d74)).
neg(carcinogen(d76)).
neg(carcinogen(d79)).
neg(carcinogen(d80)).
neg(carcinogen(d83)).
neg(carcinogen(d84)).
neg(carcinogen(d86)).
neg(carcinogen(d87)).