pos(complication(patient9)).
pos(complication(patient64)).
pos(complication(patient16)).
pos(complication(patient74)).
pos(complication(patient92)).
pos(complication(patient25)).
pos(complication(patient23)).
pos(complication(patient99)).
pos(complication(patient88)).
pos(complication(patient17)).
pos(complication(patient31)).
pos(complication(patient87)).
pos(complication(patient55)).
pos(complication(patient5)).
pos(complication(patient2)).
pos(complication(patient8)).
pos(complication(patient80)).
pos(complication(patient45)).
pos(complication(patient70)).
pos(complication(patient4)).
pos(complication(patient33)).
pos(complication(patient116)).
neg(complication(patient85)).
neg(complication(patient78)).
neg(complication(patient97)).
neg(complication(patient47)).
neg(complication(patient24)).
neg(complication(patient84)).
neg(complication(patient118)).
neg(complication(patient110)).
neg(complication(patient77)).
neg(complication(patient75)).
neg(complication(patient102)).
neg(complication(patient109)).
neg(complication(patient68)).
neg(complication(patient41)).
