pos(complication(patient13)).
pos(complication(patient20)).
pos(complication(patient91)).
pos(complication(patient10)).
pos(complication(patient72)).
pos(complication(patient89)).
pos(complication(patient19)).
pos(complication(patient71)).
pos(complication(patient36)).
pos(complication(patient83)).
pos(complication(patient43)).
pos(complication(patient21)).
pos(complication(patient30)).
pos(complication(patient117)).
pos(complication(patient42)).
pos(complication(patient115)).
pos(complication(patient104)).
pos(complication(patient54)).
pos(complication(patient112)).
pos(complication(patient69)).
pos(complication(patient95)).
pos(complication(patient81)).
neg(complication(patient108)).
neg(complication(patient100)).
neg(complication(patient62)).
neg(complication(patient53)).
neg(complication(patient61)).
neg(complication(patient106)).
neg(complication(patient38)).
neg(complication(patient51)).
neg(complication(patient79)).
neg(complication(patient76)).
neg(complication(patient113)).
neg(complication(patient101)).
neg(complication(patient29)).
neg(complication(patient56)).
